In [1]:
import pandas

In [1]:
pandas.read_csv

NameError: ignored

In [3]:
pandas.read_csv("m06_ingresos-globales-ventas-musica-grabada-segmento.csv")

,indice_tiempo,ingresos_ventas_musica_streaming,ingresos_ventas_musica_descargas,ingresos_ventas_musica_formato_fisico,ingresos_derechos_comunicacion_publica,ingresos_contratos_sincronizacion
0,2001-01-01,NaN,NaN,23.0,0.6,NaN
1,2002-01-01,NaN,NaN,21.3,0.7,NaN
2,2003-01-01,NaN,NaN,19.7,0.8,NaN
3,2004-01-01,NaN,0.4,19.1,0.9,NaN
4,2005-01-01,0.1,1.0,17.9,0.9,NaN
5,2006-01-01,0.1,2.0,16.2,1.0,NaN
6,2007-01-01,0.2,2.7,14.0,1.2,NaN
7,2008-01-01,0.3,3.4,11.9,1.2,NaN
8,2009-01-01,0.4,3.7,10.3,1.3,NaN
9,2010-01-01,0.4,3.9,8.9,1.4,0.3
10,2011-01-01,0.6,4.2,8.2,1.4,0.3
11,2012-01-01,1.0,4.4,7.6,1.5,0.3
12,2013-01-01,1.4,4.3,6.7,1.7,0.3
13,2014-01-01,1.9,4.0,6.0,1.8,0.3
14,2015-01-01,2.8,3.7,5.7,1.9,0.4
15,2016-01-01,4.6,3.2,5.5,2.2,0.4
16,2017-01-01,6.5,2.6,5.2,2.3,0.4
17,2018-01-01,9.2,1.7,4.7,2.6,0.5
18,2019-01-01,11.2,1.5,4.4,2.5,0.5
19,2020-01-01,13.4,1.2,4.2,2.3,0.4