In [25]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [26]:
file_path = "/content/drive/MyDrive/202303_PAX15min-ABC.csv"
with open(file_path, 'r') as f:
  texto = f.read()

In [27]:
texto = texto.replace('"','')

In [28]:
with open(file_path+'modificado', 'w') as f:
  f.write(texto)

In [33]:
subtes_abc = pd.read_csv(file_path+'modificado', delimiter=';')

In [34]:
subtes_abc

,FECHA,DESDE,HASTA,LINEA,MOLINETE,ESTACION,pax_pagos,pax_pases_pagos,pax_franq,pax_TOTAL
0,1/3/2023,05:15:00,05:30:00,LineaA,LineaA_CBarros_N_Turn01,Castro Barros,2,0,0,2
1,1/3/2023,05:15:00,05:30:00,LineaC,LineaC_Retiro_Turn12,Retiro,15,0,2,17
2,1/3/2023,05:15:00,05:30:00,LineaA,LineaA_Carabobo_O_Turn01,Carabobo,1,0,0,1
3,1/3/2023,05:15:00,05:30:00,LineaB,LineaB_CallaoB_S_Turn03,Callao.B,1,0,0,1
4,1/3/2023,05:15:00,05:30:00,LineaA,LineaA_SnzPena_S_Turn01,Saenz Peña,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...
574220,31/3/2023,23:30:00,23:45:00,LineaC,LineaC_Indepen_Turn04,Independencia,0,0,1,1
574221,31/3/2023,23:30:00,23:45:00,LineaC,LineaC_Retiro_Turn09,Retiro,1,0,0,1
574222,31/3/2023,23:30:00,23:45:00,LineaC,LineaC_Retiro_Turn10,Retiro,0,0,1,1
574223,31/3/2023,23:30:00,23:45:00,LineaC,LineaC_Moreno_N_Turn02,Mariano Moreno,1,0,0,1
574224,31/3/2023,23:30:00,23:45:00,LineaC,LineaC_Retiro_Turn11,Retiro,3,0,0,3