# **Grupo 4 - Ciberseguridad**
- *Belu Poma*
- *Joaco Salto*
- *Lauty Racedo*
- *Lucho Martinez*

### Temática concreta del proyecto:
Aun no decidida.

### Datos de interes:
Español:
https://es.statista.com/estadisticas/511908/sistemas-de-ciberseguridad-empleados-por-los-internautas-automatizables/
https://fedinews.com/?_=%2Ftemas%2F3166%2Fciberdelitos-en-espana%2F%23KJWqMdlUlBnuOKMGRBz0jpjhec9jFFI%3D
https://es.statista.com/estadisticas/1130614/aplicaciones-de-ai-en-ciberseguridad-de-empresas/
Ingles:
https://www.kaggle.com/katehighnam/beth-dataset/code
https://ieee-dataport.org/open-access/dataset-cyber-attacks-honeyselk
https://www.searchlogistics.com/learn/statistics/cybersecurity-statistics/
https://www.kaggle.com/datasets/zulanac/fake-and-real-news


Aca encontre algo:
https://datasetsearch.research.google.com/search?src=0&query=cyber%20attacks&docid=L2cvMTFyZ20zeXQwZg%3D%3D

**CODIGO**

In [ ]:
import pandas as pd

agua1 = pd.read_csv("test_dataset.csv")
agua2 = pd.read_csv("training_dataset_1.csv")
#agua3 = pd.read_csv("training_dataset_2.csv")

In [ ]:
agua3

,DATETIME,L_T1,L_T2,L_T3,L_T4,L_T5,L_T6,L_T7,F_PU1,S_PU1,...,P_J256,P_J289,P_J415,P_J302,P_J306,P_J307,P_J317,P_J14,P_J422,ATT_FLAG
0,04/07/16 00,2.44,5.24,3.19,4.10,2.86,5.50,4.39,93.63,1,...,70.00,28.22,85.87,21.69,82.72,21.58,71.99,39.33,29.64,0
1,04/07/16 01,2.66,4.53,3.20,4.18,3.29,5.44,4.53,89.41,1,...,87.73,24.45,84.87,29.81,86.62,29.81,59.76,42.17,26.15,0
2,04/07/16 02,3.11,3.66,3.66,4.21,3.87,5.15,3.22,89.88,1,...,89.29,23.90,87.11,29.85,87.64,29.85,58.50,42.00,25.56,0
3,04/07/16 03,3.62,3.04,4.17,4.04,3.56,4.98,2.40,88.10,1,...,91.98,27.10,68.75,31.60,64.25,31.47,72.30,43.24,28.38,0
4,04/07/16 04,4.08,2.68,4.73,3.20,3.11,5.39,3.46,87.01,1,...,92.11,26.76,68.74,32.30,64.23,32.17,72.53,44.00,28.04,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4172,24/12/16 20,2.65,2.37,3.85,3.04,3.82,4.94,2.19,120.08,1,...,70.03,27.38,84.14,18.45,81.67,18.34,66.04,29.88,28.98,0
4173,24/12/16 21,2.24,2.56,3.42,2.92,3.69,5.02,1.97,119.12,1,...,68.60,27.66,83.46,25.40,60.85,25.28,66.89,30.19,29.29,0
4174,24/12/16 22,1.91,2.76,2.95,2.49,2.70,5.14,1.87,120.71,1,...,85.63,26.84,82.82,24.46,59.56,24.34,66.08,29.68,28.78,0
4175,24/12/16 23,1.52,2.52,3.33,2.03,1.69,5.10,1.39,120.02,1,...,86.15,25.78,103.63,24.77,59.01,24.65,66.42,28.98,28.08,0
4176,25/12/16 00,1.10,2.12,3.73,2.73,1.58,5.13,1.19,120.33,1,...,89.08,25.64,105.91,18.16,80.65,18.06,67.32,28.75,27.85,0