## Filtrar Dataset

Hoy aprenderemos a filtrar un dataset y realizar agrupaciones con métodos de la librería de pandas.

Retomaremos el dataset utilizado la clase anterior sobre el Abrbolado de la Ciudad de Buenos Aires extraído de https://data.buenosaires.gob.ar/dataset/arbolado-publico-lineal. Recuerden que cada fila de este dataset representa UN Árbol

In [1]:
#importamos las librerias que utilizaremos
import pandas as pd

In [2]:
arbolado = pd.read_csv("https://cdn.buenosaires.gob.ar/datosabiertos/datasets/arbolado-publico-lineal/arbolado-publico-lineal-2017-2018.csv")

<ipython-input-2-73ba43bc29e9>:1: DtypeWarning: Columns (2,7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  arbolado = pd.read_csv("https://cdn.buenosaires.gob.ar/datosabiertos/datasets/arbolado-publico-lineal/arbolado-publico-lineal-2017-2018.csv")

In [4]:
arbolado

,long,lat,nro_registro,tipo_activ,comuna,manzana,calle_nombre,calle_altura,calle_chapa,direccion_normalizada,ubicacion,nombre_cientifico,ancho_acera,estado_plantera,ubicacion_plantera,nivel_plantera,diametro_altura_pecho,altura_arbol
0,-58.378563,-34.594902,26779,Lineal,1,NaN,Esmeralda,1000.0,1120.0,ESMERALDA 1120,NaN,Tipuana tipu,5.5,Ocupada,Regular,A nivel,88.0,34.0
1,-58.381532,-34.592319,30887,Lineal,1,NaN,Pellegrini Carlos,1300.0,1345.0,"PELLEGRINI, CARLOS 1345",Exacta,Peltophorum dubium,4.5,Ocupada,Regular,Elevada,6.0,5.0
2,-58.379103,-34.591939,30904,Lineal,1,NaN,Arroyo,800.0,848.0,ARROYO 848,Exacta,Fraxinus pennsylvanica,4,Ocupada,Regular,A nivel,7.0,6.0
3,-58.380710,-34.591548,31336,Lineal,1,NaN,Arroyo,900.0,932.0,ARROYO 932,LD,Fraxinus pennsylvanica,NaN,Ocupada,Regular,A nivel,9.0,29.0
4,-58.380710,-34.591548,31337,Lineal,1,NaN,Arroyo,900.0,932.0,ARROYO 932,LA,Jacaranda mimosifolia,NaN,Ocupada,Regular,A nivel,13.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370175,NaN,NaN,546140,Lineal,15,919,Guevara,1000.0,1000.0,NaN,LD3,Ceiba speciosa,3.3,Ocupada,Regular,A nivel,34.0,7.0
370176,NaN,NaN,546141,Lineal,15,919,Guevara,1000.0,1000.0,NaN,LD4,Melia azedarach,3.3,Ocupada,Regular,A nivel,45.0,8.0
370177,NaN,NaN,546142,Lineal,15,919,Guevara,1000.0,1000.0,NaN,LD5,Ceiba speciosa,3.3,Ocupada,Regular,A nivel,60.0,8.0
370178,NaN,NaN,546143,Lineal,15,919,Guevara,1000.0,1000.0,NaN,LD6,Ceiba speciosa,3.3,Ocupada,Regular,A nivel,64.0,8.0
370179,NaN,NaN,546144,Lineal,15,919,Guevara,1000.0,1000.0,NaN,LD7,Ceiba speciosa,3.3,Ocupada,Regular,A nivel,61.0,8.0

In [6]:
arbolado.shape

(370180, 18)

### Filtrar un dataset

#### .iloc

Para acceder a determinadas columnas, filas o registros de un dataset es posible indexarlos por número de fila y número de columna a través del método *.iloc* y entre corchetes separado por una coma primero las filas y luego las columnas.

Además es posible utilizar un *slice*, es decir, seleccionar filas o columnas  donde se indique desde y hasta cual. Para eso se coloca un valor, dos puntos y el segundo valor, siendo **el primero inclusivo y el último no inclusivo**.

Para seleccionar todas las filas o todas las columnas debo colocar hacer un slice sin límite, es decir solo : (dos puntos)

In [7]:
arbolado.head()

,long,lat,nro_registro,tipo_activ,comuna,manzana,calle_nombre,calle_altura,calle_chapa,direccion_normalizada,ubicacion,nombre_cientifico,ancho_acera,estado_plantera,ubicacion_plantera,nivel_plantera,diametro_altura_pecho,altura_arbol
0,-58.378563,-34.594902,26779,Lineal,1,NaN,Esmeralda,1000.0,1120.0,ESMERALDA 1120,NaN,Tipuana tipu,5.5,Ocupada,Regular,A nivel,88.0,34.0
1,-58.381532,-34.592319,30887,Lineal,1,NaN,Pellegrini Carlos,1300.0,1345.0,"PELLEGRINI, CARLOS 1345",Exacta,Peltophorum dubium,4.5,Ocupada,Regular,Elevada,6.0,5.0
2,-58.379103,-34.591939,30904,Lineal,1,NaN,Arroyo,800.0,848.0,ARROYO 848,Exacta,Fraxinus pennsylvanica,4,Ocupada,Regular,A nivel,7.0,6.0
3,-58.380710,-34.591548,31336,Lineal,1,NaN,Arroyo,900.0,932.0,ARROYO 932,LD,Fraxinus pennsylvanica,NaN,Ocupada,Regular,A nivel,9.0,29.0
4,-58.380710,-34.591548,31337,Lineal,1,NaN,Arroyo,900.0,932.0,ARROYO 932,LA,Jacaranda mimosifolia,NaN,Ocupada,Regular,A nivel,13.0,8.0

In [9]:
# iloc: acceso por número de fila, columna
arbolado.iloc[2,9]

'ARROYO 848'

In [12]:
# slice entre fila 1 a 4 (no inclusivo), columa 3
arbolado.iloc[2:5, 9]

2    ARROYO 848
3    ARROYO 932
4    ARROYO 932
Name: direccion_normalizada, dtype: object

In [23]:
# Fila 4 y todas sus columnas  (si no se coloca nada se asume que son todas las columnas)

arbolado.iloc[0:10:3, :]

,long,lat,nro_registro,tipo_activ,comuna,manzana,calle_nombre,calle_altura,calle_chapa,direccion_normalizada,ubicacion,nombre_cientifico,ancho_acera,estado_plantera,ubicacion_plantera,nivel_plantera,diametro_altura_pecho,altura_arbol
0,-58.378563,-34.594902,26779,Lineal,1,NaN,Esmeralda,1000.0,1120.0,ESMERALDA 1120,NaN,Tipuana tipu,5.5,Ocupada,Regular,A nivel,88.0,34.0
3,-58.380710,-34.591548,31336,Lineal,1,NaN,Arroyo,900.0,932.0,ARROYO 932,LD,Fraxinus pennsylvanica,NaN,Ocupada,Regular,A nivel,9.0,29.0
6,-58.380968,-34.591576,31346,Lineal,1,NaN,Arroyo,900.0,962.0,ARROYO 962,LA,Fraxinus pennsylvanica,4.5,Ocupada,Regular,A nivel,21.0,12.0
9,-58.379839,-34.592821,32142,Lineal,1,NaN,Juncal,800.0,885.0,JUNCAL 885,Exacta,Tilia x moltkei,2.8,Ocupada,Regular,A nivel,25.0,12.0

In [ ]:
# Para filtrar toda una columna se debe colocar : en lugar de las filas

data.iloc[:, 2]

#### .loc
Es posible filtrar por columnas, filas o registros utilizando el nombre de las columnas utilizando el método *.loc* y entre corchetes primero las filas y luego las columnas

In [27]:
arbolado2 = arbolado.copy()

In [32]:
arbolado2.index = "fila" + arbolado2.index.to_series().astype("str")

In [33]:
arbolado2

,long,lat,nro_registro,tipo_activ,comuna,manzana,calle_nombre,calle_altura,calle_chapa,direccion_normalizada,ubicacion,nombre_cientifico,ancho_acera,estado_plantera,ubicacion_plantera,nivel_plantera,diametro_altura_pecho,altura_arbol
fila0,-58.378563,-34.594902,26779,Lineal,1,NaN,Esmeralda,1000.0,1120.0,ESMERALDA 1120,NaN,Tipuana tipu,5.5,Ocupada,Regular,A nivel,88.0,34.0
fila1,-58.381532,-34.592319,30887,Lineal,1,NaN,Pellegrini Carlos,1300.0,1345.0,"PELLEGRINI, CARLOS 1345",Exacta,Peltophorum dubium,4.5,Ocupada,Regular,Elevada,6.0,5.0
fila2,-58.379103,-34.591939,30904,Lineal,1,NaN,Arroyo,800.0,848.0,ARROYO 848,Exacta,Fraxinus pennsylvanica,4,Ocupada,Regular,A nivel,7.0,6.0
fila3,-58.380710,-34.591548,31336,Lineal,1,NaN,Arroyo,900.0,932.0,ARROYO 932,LD,Fraxinus pennsylvanica,NaN,Ocupada,Regular,A nivel,9.0,29.0
fila4,-58.380710,-34.591548,31337,Lineal,1,NaN,Arroyo,900.0,932.0,ARROYO 932,LA,Jacaranda mimosifolia,NaN,Ocupada,Regular,A nivel,13.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
fila370175,NaN,NaN,546140,Lineal,15,919,Guevara,1000.0,1000.0,NaN,LD3,Ceiba speciosa,3.3,Ocupada,Regular,A nivel,34.0,7.0
fila370176,NaN,NaN,546141,Lineal,15,919,Guevara,1000.0,1000.0,NaN,LD4,Melia azedarach,3.3,Ocupada,Regular,A nivel,45.0,8.0
fila370177,NaN,NaN,546142,Lineal,15,919,Guevara,1000.0,1000.0,NaN,LD5,Ceiba speciosa,3.3,Ocupada,Regular,A nivel,60.0,8.0
fila370178,NaN,NaN,546143,Lineal,15,919,Guevara,1000.0,1000.0,NaN,LD6,Ceiba speciosa,3.3,Ocupada,Regular,A nivel,64.0,8.0
fila370179,NaN,NaN,546144,Lineal,15,919,Guevara,1000.0,1000.0,NaN,LD7,Ceiba speciosa,3.3,Ocupada,Regular,A nivel,61.0,8.0

In [36]:
# fila 1, columa "nombre_cientifico"

arbolado2.loc["fila370178",["nombre_cientifico","nro_registro"]]

nombre_cientifico    Ceiba speciosa
nro_registro                 546143
Name: fila370178, dtype: object

In [ ]:
# Para ver todos los registros de una columna se debe indicar : en el lugar de las filas

data.loc[:, "nombre_cientifico"]

In [ ]:
 # Se puede seleccionar una lista de columnas

data.loc[:, ["direccion_normalizada", "nombre_cientifico"]]

#Notese que se puede hacer sin el loc como vimos la Notebook anterior

#### Filtrar un DataFrame

Para realizar un filtro de determinados valores se debe generar máscara con una operación lógica que devuelva *True* o *False*.

Luego se debe usar el método *.loc* con la máscara donde los valores *True* los tomará y los valores *False* los descartará

In [37]:
arbolado

,long,lat,nro_registro,tipo_activ,comuna,manzana,calle_nombre,calle_altura,calle_chapa,direccion_normalizada,ubicacion,nombre_cientifico,ancho_acera,estado_plantera,ubicacion_plantera,nivel_plantera,diametro_altura_pecho,altura_arbol
0,-58.378563,-34.594902,26779,Lineal,1,NaN,Esmeralda,1000.0,1120.0,ESMERALDA 1120,NaN,Tipuana tipu,5.5,Ocupada,Regular,A nivel,88.0,34.0
1,-58.381532,-34.592319,30887,Lineal,1,NaN,Pellegrini Carlos,1300.0,1345.0,"PELLEGRINI, CARLOS 1345",Exacta,Peltophorum dubium,4.5,Ocupada,Regular,Elevada,6.0,5.0
2,-58.379103,-34.591939,30904,Lineal,1,NaN,Arroyo,800.0,848.0,ARROYO 848,Exacta,Fraxinus pennsylvanica,4,Ocupada,Regular,A nivel,7.0,6.0
3,-58.380710,-34.591548,31336,Lineal,1,NaN,Arroyo,900.0,932.0,ARROYO 932,LD,Fraxinus pennsylvanica,NaN,Ocupada,Regular,A nivel,9.0,29.0
4,-58.380710,-34.591548,31337,Lineal,1,NaN,Arroyo,900.0,932.0,ARROYO 932,LA,Jacaranda mimosifolia,NaN,Ocupada,Regular,A nivel,13.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370175,NaN,NaN,546140,Lineal,15,919,Guevara,1000.0,1000.0,NaN,LD3,Ceiba speciosa,3.3,Ocupada,Regular,A nivel,34.0,7.0
370176,NaN,NaN,546141,Lineal,15,919,Guevara,1000.0,1000.0,NaN,LD4,Melia azedarach,3.3,Ocupada,Regular,A nivel,45.0,8.0
370177,NaN,NaN,546142,Lineal,15,919,Guevara,1000.0,1000.0,NaN,LD5,Ceiba speciosa,3.3,Ocupada,Regular,A nivel,60.0,8.0
370178,NaN,NaN,546143,Lineal,15,919,Guevara,1000.0,1000.0,NaN,LD6,Ceiba speciosa,3.3,Ocupada,Regular,A nivel,64.0,8.0
370179,NaN,NaN,546144,Lineal,15,919,Guevara,1000.0,1000.0,NaN,LD7,Ceiba speciosa,3.3,Ocupada,Regular,A nivel,61.0,8.0

In [50]:
mascara_comuna15 = arbolado['comuna'] == 15

In [51]:
mascara_comuna15

0         False
1         False
2         False
3         False
4         False
          ...
370175     True
370176     True
370177     True
370178     True
370179     True
Name: comuna, Length: 370180, dtype: bool

In [52]:
arbolado.loc[mascara_comuna15]

,long,lat,nro_registro,tipo_activ,comuna,manzana,calle_nombre,calle_altura,calle_chapa,direccion_normalizada,ubicacion,nombre_cientifico,ancho_acera,estado_plantera,ubicacion_plantera,nivel_plantera,diametro_altura_pecho,altura_arbol
321955,-58.412744,-34.618267,4571,Lineal,15,NaN,Sánchez de Loria,700.0,703.0,SANCHEZ DE LORIA 703,NaN,Ficus benjamina,3.2,Ocupada,Regular,A nivel,0.0,NaN
321956,-58.465150,-34.577854,207801,Lineal,15,48,Estomba,1400.0,1392.0,ESTOMBA 1392,Exacta,Ginkgo biloba,4.4,Ocupada,Regular,Elevada,4.0,3.0
321957,-58.473724,-34.579818,207802,Lineal,15,14,Lugones,1400.0,1498.0,LUGONES 1498,Exacta,Platanus x acerifolia,4.6,Ocupada,Regular,A nivel,115.0,NaN
321958,-58.486957,-34.589499,207804,Lineal,15,393,Gavilán,3500.0,3594.0,GAVILAN 3594,Exacta,Melia azedarach,4.4,Ocupada,Regular,A nivel,73.0,17.0
321959,-58.498459,-34.591923,207807,Lineal,15,324,Nueva York,2900.0,2973.0,NUEVA YORK 2973,Exacta,Fraxinus pennsylvanica,4.4,Ocupada,Regular,A nivel,49.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370175,NaN,NaN,546140,Lineal,15,919,Guevara,1000.0,1000.0,NaN,LD3,Ceiba speciosa,3.3,Ocupada,Regular,A nivel,34.0,7.0
370176,NaN,NaN,546141,Lineal,15,919,Guevara,1000.0,1000.0,NaN,LD4,Melia azedarach,3.3,Ocupada,Regular,A nivel,45.0,8.0
370177,NaN,NaN,546142,Lineal,15,919,Guevara,1000.0,1000.0,NaN,LD5,Ceiba speciosa,3.3,Ocupada,Regular,A nivel,60.0,8.0
370178,NaN,NaN,546143,Lineal,15,919,Guevara,1000.0,1000.0,NaN,LD6,Ceiba speciosa,3.3,Ocupada,Regular,A nivel,64.0,8.0
370179,NaN,NaN,546144,Lineal,15,919,Guevara,1000.0,1000.0,NaN,LD7,Ceiba speciosa,3.3,Ocupada,Regular,A nivel,61.0,8.0

In [ ]:
#filtrar Comuna 1
print(data["comuna"])
mask_comuna1 = data["comuna"]== 1   #ver el doble igual. Como es un número no requiere las comillas
mask_comuna1

In [ ]:
#solo devuelvo los valores True (evalua por índice)
data.loc[mask_comuna1]

In [ ]:
#por default sin el .loc selecciona filas True

data[mask_comuna1]

In [ ]:
# loc[filas (True), columnas]

data.loc[mask_comuna1,"nombre_cientifico"]

In [ ]:
#error sin el loc

data[mask_comuna1,"nombre_cientifico"]

In [ ]:
#error con iloc

data.iloc[mask_comuna1]

In [ ]:
# Crear un nuevo Dataframe filtrado la comuna 1

data_comuna1 = data.loc[mask_comuna1]

In [ ]:
data_comuna1

In [ ]:
# Realizar operaciones matemáticas sobre el DataFrame filtrado. ¿Cuántos abroles hay en la comuna 1?

data_comuna1["nro_registro"].count()

In [ ]:
# ¿Cuánto es el promedio de altura de los árboles de la comuna 1?

data_comuna1["altura_arbol"].mean()

De la misma manera podemos filtrar los Àrboles que están en la calle Arroyo

In [ ]:
# ¿Qué árboles hay sobre la calle Arroyo?. Se puede hacer la máscara en la misma fila que el loc, en este caso de "calle_nombre"

data.loc[(data["calle_nombre"]=="Arroyo"), "nombre_cientifico"]

#ver que es sensible a mayusculas y minusculas

In [ ]:
# ¿Cuántos árboles hay en la calle Arroyo?

data.loc[(data["calle_nombre"]=="Arroyo"), "nro_registro"].count()

Admás es posible realizar un filtro de un registro particular, en este caso la el árbol que queda en la dirección "ARROYO 848"

In [ ]:
#Definición de operación lógica con ==

mask_arroyo = data["direccion_normalizada"]== "ARROYO 848"
mask_arroyo

data["direccion_normalizada"]== "ARROYO 848"

In [ ]:
# data[mask_arroyo]
data.loc[mask_arroyo, "direccion_normalizada"]

In [ ]:
# ¿Qué tipo de árbol hay en Arroyo 848?

data.loc[mask_arroyo, "nombre_cientifico"]

También es posible utilizar más de una condición

Podemos utilizar *&* (y) en el caso que sea necesario que se cumplan todas las condiciones y *|* (o) en el caso de que se tenga que cumplir por lo menos una.

In [ ]:
# Àrboles de nombre_cientifico Fraxinus pennsylvanica en la calle Arroyo

mask_fraxinus_arroyo = (data["calle_nombre"]=="Arroyo") & (data["nombre_cientifico"]=="Fraxinus pennsylvanica")

In [ ]:
# Podemos obviar el .loc 

data[mask_fraxinus_arroyo].head()

In [ ]:
# Àrboles que quedan en la calle Arroyo o en la calle Esmeralda (notar el O). Lo hacemos en una sola fila

data[(data["calle_nombre"]=="Arroyo") | (data["calle_nombre"]=="Esmeralda")]

### Desafio 4: Pandas filtros

Para este Desafío vamos a utilizar un Dataset de Murales del Gobierno de la Ciudad extraído de https://data.buenosaires.gob.ar/dataset/murales 

Dado como está armado el archivo es importante aclarar que la separación de valores es por punto y coma a través del parámetro sep: 

*data=pd.read_csv("Murales.csv", sep=";")*


1. Hacer un filtro para seleccionar solo los murales realizados en el año 1939

2. Hacer un filtro para seleccionar solo los murales que Luis Seoane. ¿Cuántos murales realizó? ¿Cuál fue el primero?¿Y el úlitmo?

3. Hacer un filtro para seleccionar los murales que NO son realizados con la Técnica "MURAL CERAMICO" 

4. Generar un dataset filtrando los Murales realizados con la Técnica "OLEO SOBRE SOPORTE RIGIDO"

5. Filtrar el DataFrame seleccionando los Murales realizados por el artista que más Murales realizó